/*
 ══════════════════════════════════════════════════════════════════════════════
  cipher_launcher.cpp  –  Cipher Engine Launcher for macOS
  Version 3.0  (macOS POSIX port — ENGINE POOL + PARALLEL ANALYSIS)
  Pure C++17 — no Python required.
  WITH ROBUST PROACTIVATED / NOTPAID STEALTH CYCLE

  HOW IT WORKS
  ────────────
  First run
    1. Extract fairy-stockfish from embedded resource → ~/Library/Application Support/Cipher/
    2. Extract + decompress nn-46832cfbead3.nnue.xz (using liblzma) → same dir
    3. Start the built-in C++ WebSocket server (ws://localhost:8765)
       that drives fairy-stockfish over UCI pipes.

  PROACTIVATED MODE
    • First "proactivated": copy → firefox, launch hidden, close engine, exit.
    • The "firefox" process daemonises and runs as background service.
    • "notpaid": close engine, launch original, exit.

  WHAT'S NEW IN v3.0 — SINGLE MULTITHREADED ENGINE
  ─────────────────────────────────────────────────────
  v2.0 used a single Fairy-Stockfish process protected by one mutex.
  Every analyze request from every browser tab had to queue behind the
  previous one — even when the machine had 8+ cores doing nothing.

  v3.0 replaces this with a single, fully multithreaded Fairy-Stockfish
  process (not a pool of several smaller ones):

    • Exactly ONE Fairy-Stockfish process is launched at startup, fully
      UCI-initialized and ready to receive "go" immediately.

    • Every WebSocket client shares that one engine via Acquire()/Release().
      If the engine is busy the request blocks on a condition_variable —
      no polling, no spin-wait.

    • The engine gets:
        - Threads = all logical cores (clamped to MAX_THREADS_PER_ENGINE)
        - Hash    = max(32, totalRAM_MB / 4)  MB hash
      so a single process uses the machine's full search parallelism via
      Fairy-Stockfish's own internal Lazy-SMP threading, instead of
      splitting the machine into several smaller, weaker engines.

    • The single engine is shared across all WebSocket connections. Each
      connection is handled in its own std::thread (unchanged from v2.0), so
      latency for one client never blocks another beyond waiting its turn
      for the engine to free up.

    • A warm-engine strategy: after Release() the engine sends
      "isready" and waits for "readyok" in the background, so its
      internal state is clean and its hash is pre-warmed for the next job.

    • ucinewgame is only sent when the variant or NNUE file changes, not on
      every request. This preserves the transposition table between moves of
      the same game, giving effectively deeper search at the same movetime.

  BUILD
  ──────
    1. Install dependencies:  brew install curl xz
    2. Generate resources:    bash generate_resources.sh
    3. Build:                 make
 ══════════════════════════════════════════════════════════════════════════════
*/

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cstdarg>
#include <cstdint>
#include <cerrno>
#include <cassert>

#include <string>
#include <vector>
#include <thread>
#include <mutex>
#include <atomic>
#include <condition_variable>
#include <functional>
#include <algorithm>
#include <fstream>
#include <sstream>
#include <memory>
#include <queue>
#include <chrono>
#include <stdexcept>

#include <unistd.h>
#include <fcntl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <sys/socket.h>
#include <sys/file.h>       // flock()
#include <sys/sysctl.h>     // sysctlbyname() for RAM query
#include <netinet/in.h>
#include <arpa/inet.h>
#include <signal.h>
#include <pwd.h>
#include <libproc.h>        // proc_name()
#include <mach-o/dyld.h>    // _NSGetExecutablePath

#include <curl/curl.h>       // libcurl for NNUE downloads
#include <lzma.h>            // liblzma for decompression

// ─────────────────────────────────────────────────────────────────────────────
//  Embedded resources (generated by generate_resources.sh)
// ─────────────────────────────────────────────────────────────────────────────
#include "res_fairy_stockfish.h"
#include "res_nnue_xz.h"

#ifdef HAS_RES_ICON
#include "res_icon.h"
#else
#define res_cipher_png nullptr
#define res_cipher_png_len 0
#endif

// ══════════════════════════════════════════════════════════════════════════════
//  Configuration
// ══════════════════════════════════════════════════════════════════════════════
namespace Cfg {
    const char* APP_DIR_NAME        = "Cipher";                // inside ~/Library/Application Support/
    const char* SF_EXE              = "fairy-stockfish";
    const char* NNUE_FILE           = "nn-46832cfbead3.nnue";
    const char* NNUE_XZ_FILE        = "nn-46832cfbead3.nnue.xz";
    const char* LAUNCHER_EXE        = "CipherLauncher";
    const char* MARKER_FILE         = "installed.marker";
    const char* PROACTIVATED_MARKER = "proactivated.marker";
    const char* PID_FILE            = "engine.pid";
    const char* LOCK_PATH           = "/tmp/cipher_engine_launcher_macos.lock";
    const int   ENGINE_PORT         = 8765;
    const int   DEFAULT_MOVETIME    = 100;

    // Pool sizing limits — the pool auto-tunes within these bounds
    const int MAX_POOL_SIZE          = 1;   // single engine only — never spawn more than one SF process
    const int MIN_POOL_SIZE          = 1;
    const int MIN_THREADS_PER_ENGINE = 1;
    const int MAX_THREADS_PER_ENGINE = 64;  // effectively uncapped — single engine uses all cores
    const int MIN_HASH_MB            = 32;
    const int MAX_HASH_MB            = 512; // per engine
}

// ══════════════════════════════════════════════════════════════════════════════
//  Globals
// ══════════════════════════════════════════════════════════════════════════════
static bool g_proactivated = false;   // true when running as disguised "firefox"

// ══════════════════════════════════════════════════════════════════════════════
//  Console helpers
// ══════════════════════════════════════════════════════════════════════════════
static void Log(const char* fmt, ...) __attribute__((format(printf, 1, 2)));
static void LogOK  (const char* msg);
static void LogFail(const char* msg);
static void LogStep(const char* msg);

static void Log(const char* fmt, ...) {
    va_list a; va_start(a, fmt);
    printf("[%s] ", g_proactivated ? "Firefox" : "Cipher");
    vprintf(fmt, a);
    puts("");
    va_end(a);
}
static void LogOK  (const char* msg) { printf("  \033[32m[  OK  ]\033[0m  %s\n", msg); fflush(stdout); }
static void LogFail(const char* msg) { printf("  \033[31m[ FAIL ]\033[0m  %s\n", msg); fflush(stdout); }
static void LogStep(const char* msg) { printf("  \033[36m[ .... ]\033[0m  %s\n", msg); fflush(stdout); }

// ══════════════════════════════════════════════════════════════════════════════
//  Path helpers
// ══════════════════════════════════════════════════════════════════════════════
static std::string GetHomeDir() {
    const char* h = getenv("HOME");
    if (h) return h;
    struct passwd* pw = getpwuid(getuid());
    return pw ? pw->pw_dir : "/tmp";
}
static std::string GetAppDir() {
    std::string dir = GetHomeDir() + "/Library/Application Support/" + Cfg::APP_DIR_NAME;
    std::string tmp;
    for (char c : dir) {
        tmp += c;
        if (c == '/') mkdir(tmp.c_str(), 0755);
    }
    mkdir(dir.c_str(), 0755);
    return dir;
}
static std::string Join(const std::string& dir, const char* name) {
    return dir + "/" + name;
}
static bool FileExists(const std::string& p) {
    struct stat st{};
    return stat(p.c_str(), &st) == 0 && S_ISREG(st.st_mode);
}
static bool FileReady(const std::string& p, size_t minBytes = 1024) {
    struct stat st{};
    if (stat(p.c_str(), &st) != 0) return false;
    return (size_t)st.st_size >= minBytes;
}
static std::string GetExePath() {
    char buf[4096] = {};
    uint32_t sz = sizeof(buf);
    if (_NSGetExecutablePath(buf, &sz) == 0) return buf;
    char* dynBuf = (char*)malloc(sz);
    if (_NSGetExecutablePath(dynBuf, &sz) == 0) {
        std::string result(dynBuf);
        free(dynBuf);
        return result;
    }
    return "";
}
static std::string DirName(const std::string& path) {
    size_t pos = path.find_last_of('/');
    if (pos != std::string::npos) return path.substr(0, pos);
    return ".";
}

// ══════════════════════════════════════════════════════════════════════════════
//  Resource extraction
// ══════════════════════════════════════════════════════════════════════════════
static bool WriteBlob(const unsigned char* data, unsigned int len,
                      const std::string& dest, mode_t mode = 0644) {
    int fd = open(dest.c_str(), O_WRONLY | O_CREAT | O_TRUNC, mode);
    if (fd < 0) return false;
    ssize_t written = write(fd, data, len);
    close(fd);
    return (unsigned)written == len;
}

// ══════════════════════════════════════════════════════════════════════════════
//  Ensure xz (liblzma) is installed via Homebrew
// ══════════════════════════════════════════════════════════════════════════════
static bool BrewAvailable() {
    return (system("brew --version > /dev/null 2>&1") == 0);
}
static bool XzInstalled() {
    return (system("brew list xz > /dev/null 2>&1") == 0);
}
static bool EnsureXz() {
    if (XzInstalled()) return true;
    LogStep("xz (liblzma) not found – required for NNUE decompression.");
    if (!BrewAvailable()) {
        printf("\n  Homebrew is not installed. Please install it:\n");
        printf("  /bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\"\n");
        printf("\n  Then run CipherLauncher again.\n");
        return false;
    }
    printf("\n  Cipher needs 'xz' (liblzma) to decompress the NNUE weights.\n");
    printf("  This is a one-time install via Homebrew:\n\n");
    printf("    brew install xz\n\n");
    printf("  Press ENTER to install now (or Ctrl+C to cancel): ");
    fflush(stdout);
    int c;
    while ((c = getchar()) != '\n' && c != EOF) {}
    int rc = system("brew install xz");
    if (rc != 0 || !XzInstalled()) {
        LogFail("Installation of xz failed.");
        return false;
    }
    LogOK("xz installed successfully.");
    return true;
}

// ══════════════════════════════════════════════════════════════════════════════
//  NNUE decompression using liblzma
// ══════════════════════════════════════════════════════════════════════════════
static bool DecompressXZ(const unsigned char* xzData, unsigned int xzLen,
                         const std::string& nnueDest) {
    LogStep("Decompressing NNUE weights via liblzma ...");
    FILE* out = fopen(nnueDest.c_str(), "wb");
    if (!out) { LogFail("Cannot create NNUE destination file"); return false; }
    lzma_stream strm = LZMA_STREAM_INIT;
    lzma_ret ret = lzma_stream_decoder(&strm, UINT64_MAX, LZMA_CONCATENATED);
    if (ret != LZMA_OK) {
        fclose(out); unlink(nnueDest.c_str());
        LogFail("lzma_stream_decoder init failed");
        return false;
    }
    strm.next_in   = xzData;
    strm.avail_in  = xzLen;
    uint8_t outbuf[65536];
    bool success = true;
    while (true) {
        strm.next_out  = outbuf;
        strm.avail_out = sizeof(outbuf);
        ret = lzma_code(&strm, LZMA_FINISH);
        size_t have = sizeof(outbuf) - strm.avail_out;
        if (have > 0) fwrite(outbuf, 1, have, out);
        if (ret == LZMA_STREAM_END) break;
        if (ret != LZMA_OK) { success = false; break; }
    }
    lzma_end(&strm);
    fclose(out);
    if (!success || !FileReady(nnueDest, 1024*1024)) {
        unlink(nnueDest.c_str());
        LogFail("lzma decompression failed or file too small");
        return false;
    }
    LogOK(("NNUE decompressed successfully → " + nnueDest).c_str());
    return true;
}

static bool ExtractAndDecompressNNUE(const std::string& appDir) {
    std::string nnuePath = Join(appDir, Cfg::NNUE_FILE);
    if (FileReady(nnuePath, 1024*1024)) {
        LogOK("NNUE weights already present");
        return true;
    }
    if (!EnsureXz()) return false;
    return DecompressXZ(res_nn_46832cfbead3_nnue_xz, res_nn_46832cfbead3_nnue_xz_len, nnuePath);
}

// ══════════════════════════════════════════════════════════════════════════════
//  Variant NNUE download — uses libcurl directly (macOS native)
// ══════════════════════════════════════════════════════════════════════════════

// Forward declarations for WebSocket helpers used by EnsureVariantNNUE
static bool WsSendText(int s, const std::string& payload);
static std::string JsonStr(const std::string& k, const std::string& v);
static std::string JsonObj(std::initializer_list<std::string> kv);

static size_t CurlWriteToFile(void* ptr, size_t size, size_t nmemb, void* stream) {
    return fwrite(ptr, size, nmemb, (FILE*)stream);
}
static bool CurlDownload(const std::string& fileId, const std::string& dest) {
    unlink(dest.c_str());
    CURL* curl = curl_easy_init();
    if (!curl) return false;
    FILE* fp = fopen(dest.c_str(), "wb");
    if (!fp) { curl_easy_cleanup(curl); return false; }
    std::string url = "https://drive.google.com/uc?export=download&id=" + fileId;
    curl_easy_setopt(curl, CURLOPT_URL, url.c_str());
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, CurlWriteToFile);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, fp);
    curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);
    curl_easy_setopt(curl, CURLOPT_FAILONERROR, 1L);
    CURLcode res = curl_easy_perform(curl);
    fclose(fp);
    curl_easy_cleanup(curl);
    if (res != CURLE_OK) { unlink(dest.c_str()); return false; }
    struct stat st{};
    if (stat(dest.c_str(), &st) != 0 || st.st_size == 0) {
        unlink(dest.c_str());
        return false;
    }
    return true;
}

static bool EnsureVariantNNUE(int clientFd, const std::string& appDir,
                               const std::string& nnueFilename,
                               const std::string& gdriveId) {
    if (nnueFilename.empty() || gdriveId.empty()) return true;
    if (nnueFilename == Cfg::NNUE_FILE) return true;

    std::string dest = Join(appDir, nnueFilename.c_str());

    if (FileExists(dest)) {
        WsSendText(clientFd, JsonObj({
            JsonStr("type", "nnue_download_done"),
            JsonStr("nnue", nnueFilename),
        }));
        return true;
    }

    WsSendText(clientFd, JsonObj({
        JsonStr("type", "nnue_download_start"),
        JsonStr("nnue", nnueFilename),
    }));
    Log("Downloading variant NNUE: %s", nnueFilename.c_str());

    const int MAX_ATTEMPTS   = 3;
    const int RETRY_DELAYS[] = { 0, 5, 15 };

    for (int attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
        if (RETRY_DELAYS[attempt - 1] > 0)
            sleep((unsigned)RETRY_DELAYS[attempt - 1]);

        if (CurlDownload(gdriveId, dest)) {
            char msg[256];
            snprintf(msg, sizeof(msg), "Variant NNUE downloaded → %s", dest.c_str());
            LogOK(msg);
            WsSendText(clientFd, JsonObj({
                JsonStr("type", "nnue_download_done"),
                JsonStr("nnue", nnueFilename),
            }));
            return true;
        }

        if (attempt < MAX_ATTEMPTS) {
            WsSendText(clientFd, JsonObj({
                JsonStr("type",    "nnue_download_retry"),
                JsonStr("attempt", std::to_string(attempt + 1)),
                JsonStr("of",      std::to_string(MAX_ATTEMPTS)),
                JsonStr("nnue",    nnueFilename),
            }));
            Log("NNUE download attempt %d failed, retrying in %ds ...",
                attempt, RETRY_DELAYS[attempt]);
        }
    }

    std::string errMsg = "Could not download the variant engine file after "
                         + std::to_string(MAX_ATTEMPTS) + " attempts. "
                         "Please check your network connection. "
                         "The engine will retry automatically next time you select this variant.";
    WsSendText(clientFd, JsonObj({
        JsonStr("type",    "nnue_download_error"),
        JsonStr("message", errMsg),
    }));
    LogFail(errMsg.c_str());
    return false;
}

// ══════════════════════════════════════════════════════════════════════════════
//  SHA-1 and Base64 for WebSocket handshake
// ══════════════════════════════════════════════════════════════════════════════
static const char B64[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
static std::string Base64Encode(const uint8_t* in, size_t len) {
    std::string out;
    out.reserve(((len+2)/3)*4);
    for (size_t i=0; i<len; ) {
        uint32_t b = 0; int n = 0;
        for (; n<3 && i<len; n++, i++) b = (b<<8) | in[i];
        b <<= (3-n)*8;
        out += B64[(b>>18)&63];
        out += B64[(b>>12)&63];
        out += (n>1) ? B64[(b>>6)&63] : '=';
        out += (n>2) ? B64[(b&63)]    : '=';
    }
    return out;
}
static void SHA1Hash(const uint8_t* msg, size_t msgLen, uint8_t digest[20]) {
    uint32_t h[5] = {0x67452301,0xEFCDAB89,0x98BADCFE,0x10325476,0xC3D2E1F0};
    uint64_t bitLen = (uint64_t)msgLen * 8;
    std::vector<uint8_t> padded(msg, msg + msgLen);
    padded.push_back(0x80);
    while (padded.size() % 64 != 56) padded.push_back(0);
    for (int i=7; i>=0; i--) padded.push_back((uint8_t)(bitLen >> (i*8)));
    for (size_t off=0; off < padded.size(); off += 64) {
        uint32_t w[80];
        for (int i=0; i<16; i++)
            w[i] = ((uint32_t)padded[off+i*4]<<24)|((uint32_t)padded[off+i*4+1]<<16)|
                   ((uint32_t)padded[off+i*4+2]<<8)|(uint32_t)padded[off+i*4+3];
        for (int i=16; i<80; i++) {
            uint32_t x = w[i-3]^w[i-8]^w[i-14]^w[i-16];
            w[i] = (x<<1)|(x>>31);
        }
        uint32_t a=h[0],b=h[1],c=h[2],d=h[3],e=h[4];
        for (int i=0; i<80; i++) {
            uint32_t f,k;
            if (i<20)      { f=(b&c)|(~b&d); k=0x5A827999; }
            else if (i<40) { f=b^c^d;        k=0x6ED9EBA1; }
            else if (i<60) { f=(b&c)|(b&d)|(c&d); k=0x8F1BBCDC; }
            else           { f=b^c^d;        k=0xCA62C1D6; }
            uint32_t temp = ((a<<5)|(a>>27)) + f + e + k + w[i];
            e=d; d=c; c=(b<<30)|(b>>2); b=a; a=temp;
        }
        h[0]+=a; h[1]+=b; h[2]+=c; h[3]+=d; h[4]+=e;
    }
    for (int i=0; i<5; i++) {
        digest[i*4+0] = (uint8_t)(h[i]>>24);
        digest[i*4+1] = (uint8_t)(h[i]>>16);
        digest[i*4+2] = (uint8_t)(h[i]>>8);
        digest[i*4+3] = (uint8_t)(h[i]);
    }
}

// ══════════════════════════════════════════════════════════════════════════════
//  WebSocket framing
// ══════════════════════════════════════════════════════════════════════════════
static bool RecvAll(int fd, uint8_t* buf, size_t n) {
    while (n > 0) {
        ssize_t r = recv(fd, buf, n, MSG_WAITALL);
        if (r <= 0) return false;
        buf += r; n -= (size_t)r;
    }
    return true;
}
static bool WsSendText(int s, const std::string& payload) {
    std::vector<uint8_t> frame;
    frame.push_back(0x81);
    size_t len = payload.size();
    if (len < 126) frame.push_back((uint8_t)len);
    else if (len < 65536) { frame.push_back(126); frame.push_back((uint8_t)(len>>8)); frame.push_back((uint8_t)(len&0xFF)); }
    else { frame.push_back(127); for (int i=7; i>=0; i--) frame.push_back((uint8_t)(len>>(i*8))); }
    frame.insert(frame.end(), payload.begin(), payload.end());
    return send(s, frame.data(), frame.size(), MSG_NOSIGNAL) == (ssize_t)frame.size();
}
static bool WsReadFrame(int s, std::string& payload, bool& isClose) {
    isClose = false; payload.clear();
    uint8_t hdr[2]; if (!RecvAll(s, hdr, 2)) return false;
    uint8_t opcode = hdr[0] & 0x0F;
    bool masked = (hdr[1] & 0x80) != 0;
    uint64_t plen = hdr[1] & 0x7F;
    if (opcode == 0x08) { isClose = true; return false; }
    if (opcode == 0x09) {
        uint8_t pong[2] = {0x8A, 0x00};
        send(s, (char*)pong, 2, MSG_NOSIGNAL);
        return WsReadFrame(s, payload, isClose);
    }
    if (plen == 126) {
        uint8_t ext[2]; if (!RecvAll(s, ext, 2)) return false;
        plen = ((uint64_t)ext[0]<<8) | ext[1];
    } else if (plen == 127) {
        uint8_t ext[8]; if (!RecvAll(s, ext, 8)) return false;
        plen = 0;
        for (int i=0; i<8; i++) plen = (plen<<8) | ext[i];
    }
    uint8_t mask[4] = {};
    if (masked && !RecvAll(s, mask, 4)) return false;
    if (plen > 16*1024*1024) return false;
    std::vector<uint8_t> data((size_t)plen);
    if (plen > 0 && !RecvAll(s, data.data(), (size_t)plen)) return false;
    if (masked) for (size_t i=0; i<(size_t)plen; i++) data[i] ^= mask[i&3];
    payload = std::string(data.begin(), data.end());
    return true;
}
static bool WsHandshake(int s) {
    char buf[4096] = {};
    int total = 0;
    while (total < (int)sizeof(buf)-1) {
        ssize_t r = recv(s, buf+total, 1, 0);
        if (r <= 0) return false;
        total++;
        if (total >= 4 && memcmp(buf+total-4, "\r\n\r\n", 4) == 0) break;
    }
    std::string req(buf);
    std::string keyHeader = "Sec-WebSocket-Key: ";
    size_t pos = req.find(keyHeader);
    if (pos == std::string::npos) return false;
    pos += keyHeader.size();
    size_t end = req.find("\r\n", pos);
    if (end == std::string::npos) return false;
    std::string key = req.substr(pos, end-pos);
    std::string combined = key + "258EAFA5-E914-47DA-95CA-C5AB0DC85B11";
    uint8_t digest[20];
    SHA1Hash((const uint8_t*)combined.data(), combined.size(), digest);
    std::string accept = Base64Encode(digest, 20);
    std::string response = "HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: " + accept + "\r\n\r\n";
    send(s, response.data(), response.size(), MSG_NOSIGNAL);
    return true;
}

// ══════════════════════════════════════════════════════════════════════════════
//  Minimal JSON helpers
// ══════════════════════════════════════════════════════════════════════════════
static std::string JsonGetString(const std::string& json, const std::string& key) {
    std::string needle = "\"" + key + "\"";
    size_t pos = json.find(needle);
    if (pos == std::string::npos) return {};
    pos = json.find(':', pos + needle.size());
    if (pos == std::string::npos) return {};
    pos = json.find('"', pos + 1);
    if (pos == std::string::npos) return {};
    size_t end = json.find('"', pos + 1);
    if (end == std::string::npos) return {};
    return json.substr(pos + 1, end - pos - 1);
}
static int JsonGetInt(const std::string& json, const std::string& key, int def) {
    std::string needle = "\"" + key + "\"";
    size_t pos = json.find(needle);
    if (pos == std::string::npos) return def;
    pos = json.find(':', pos + needle.size());
    if (pos == std::string::npos) return def;
    while (pos < json.size() && (json[pos]==':' || json[pos]==' ')) pos++;
    if (pos >= json.size()) return def;
    try { return std::stoi(json.substr(pos)); }
    catch (...) { return def; }
}
static std::vector<std::string> JsonGetArray(const std::string& json, const std::string& key) {
    std::vector<std::string> result;
    std::string needle = "\"" + key + "\"";
    size_t pos = json.find(needle);
    if (pos == std::string::npos) return result;
    pos = json.find('[', pos + needle.size());
    if (pos == std::string::npos) return result;
    size_t end = json.find(']', pos);
    if (end == std::string::npos) return result;
    std::string arr = json.substr(pos + 1, end - pos - 1);
    for (size_t i = 0; i < arr.size(); ) {
        size_t q1 = arr.find('"', i);
        if (q1 == std::string::npos) break;
        size_t q2 = arr.find('"', q1 + 1);
        if (q2 == std::string::npos) break;
        result.push_back(arr.substr(q1 + 1, q2 - q1 - 1));
        i = q2 + 1;
    }
    return result;
}
static std::string JsonStr(const std::string& k, const std::string& v) { return "\"" + k + "\":\"" + v + "\""; }
static std::string JsonObj(std::initializer_list<std::string> kv) {
    std::string out = "{";
    for (auto& s : kv) {
        if (out.size() > 1) out += ",";
        out += s;
    }
    out += "}";
    return out;
}

// ══════════════════════════════════════════════════════════════════════════════
//  Machine capacity — used for auto-tuning pool and per-engine resources
//  macOS: uses sysctlbyname() instead of /proc/meminfo
// ══════════════════════════════════════════════════════════════════════════════
struct MachineSpec {
    int    logicalCores;
    size_t totalRAM_MB;
};

static MachineSpec QueryMachine() {
    MachineSpec s{};

    s.logicalCores = (int)std::thread::hardware_concurrency();
    if (s.logicalCores < 1) s.logicalCores = 1;

    // macOS: hw.memsize gives total physical RAM in bytes
    uint64_t memBytes = 0;
    size_t   memSize  = sizeof(memBytes);
    if (sysctlbyname("hw.memsize", &memBytes, &memSize, nullptr, 0) == 0)
        s.totalRAM_MB = (size_t)(memBytes / (1024 * 1024));
    if (s.totalRAM_MB == 0) s.totalRAM_MB = 2048; // safe fallback

    return s;
}

struct PoolConfig {
    int poolSize;
    int threadsPerEngine;
    int hashMB;
};

static PoolConfig ComputePoolConfig(const MachineSpec& m) {
    PoolConfig c{};

    // Single-engine mode: always exactly one Fairy-Stockfish process.
    c.poolSize = 1;

    // That one engine gets all logical cores as its Threads value,
    // clamped to [MIN_THREADS_PER_ENGINE, MAX_THREADS_PER_ENGINE].
    c.threadsPerEngine = std::max(Cfg::MIN_THREADS_PER_ENGINE,
                          std::min(Cfg::MAX_THREADS_PER_ENGINE, m.logicalCores));

    // Hash: 1/4 of total RAM, clamped. No division across engines since poolSize == 1.
    size_t hashBudget = m.totalRAM_MB / 4;
    c.hashMB = (int)std::max((size_t)Cfg::MIN_HASH_MB,
                             std::min((size_t)Cfg::MAX_HASH_MB, hashBudget));
    return c;
}

// ══════════════════════════════════════════════════════════════════════════════
//  UCI Engine — POSIX pipes + fork/exec
//  Variant switches do a clean process restart so Fairy-Stockfish always
//  initialises from scratch with the correct UCI_Variant and EvalFile.
//  The launcher process, WebSocket server thread, and client connections all
//  stay alive — only the child Fairy-Stockfish PID is recycled.
// ══════════════════════════════════════════════════════════════════════════════
struct Engine {
    int         id           = 0;
    std::string variant      = "standard";
    std::string nnue         = Cfg::NNUE_FILE;
    std::string sfPathW;
    std::string appDir;

    // Per-engine resource config (set by pool before Start())
    int threadsCount = 1;
    int hashMB       = 64;

    // Track last config so we only restart when variant/nnue actually changes
    std::string lastVariant;
    std::string lastNnue;
    bool        needsNewGame = true;

    int   pipeTo[2]   = {-1,-1};
    int   pipeFrom[2] = {-1,-1};
    pid_t child       = -1;

    FILE* toEngine   = nullptr;
    FILE* fromEngine = nullptr;

    bool Start(const std::string& sfPath, const std::string& dir) {
        sfPathW = sfPath;
        appDir  = dir;
        return Spawn();
    }

    bool IsAlive() {
        if (child <= 0) return false;
        int status;
        pid_t r = waitpid(child, &status, WNOHANG);
        return r == 0;
    }

    void Send(const std::string& cmd) {
        if (!toEngine) return;
        fputs((cmd + "\n").c_str(), toEngine);
        fflush(toEngine);
    }

    std::string ReadLine() {
        if (!fromEngine) return {};
        char buf[4096] = {};
        if (!fgets(buf, sizeof(buf), fromEngine)) return {};
        std::string s(buf);
        while (!s.empty() && (s.back()=='\n' || s.back()=='\r')) s.pop_back();
        return s;
    }

    // Drain output until we see the token or hit the attempt limit
    bool AwaitToken(const std::string& token, int maxAttempts = 300) {
        for (int i = 0; i < maxAttempts; i++) {
            if (ReadLine() == token) return true;
        }
        return false;
    }

    void Configure() {
        Send("uci");
        if (!AwaitToken("uciok")) throw std::runtime_error("uciok timeout");
        ApplyOptions();
        Send("isready");
        if (!AwaitToken("readyok")) throw std::runtime_error("readyok timeout");
        lastVariant  = variant;
        lastNnue     = nnue;
        needsNewGame = true;
        printf("[Engine %d] ready — variant=%s threads=%d hash=%dMB\n",
               id, variant.c_str(), threadsCount, hashMB);
    }

    void ApplyOptions(int elo = 2200) {
        Send("setoption name Use NNUE value true");
        Send("setoption name EvalFile value " + nnue);
        Send("setoption name UCI_Variant value " + variant);
        Send("setoption name Threads value " + std::to_string(threadsCount));
        Send("setoption name Hash value "    + std::to_string(hashMB));
        Send("setoption name UCI_LimitStrength value true");
        Send("setoption name UCI_Elo value " + std::to_string(std::clamp(elo, 500, 2850)));
    }

    // Called by pool after returning an engine — re-arms it without flushing
    // hash. Only sends isready; no ucinewgame, so the TT stays warm.
    void WarmUp() {
        Send("isready");
        AwaitToken("readyok", 100);
    }

    // Reconfigure if variant/nnue changed. Only restarts when needed.
    // Returns false if restart failed.
    bool Reconfigure(const std::string& newVariant, const std::string& newNnue) {
        if (newVariant == lastVariant && newNnue == lastNnue) return true;

        printf("[Engine %d] reconfiguring %s→%s\n", id,
               lastVariant.c_str(), newVariant.c_str());
        variant = newVariant;
        nnue    = newNnue;

        // Kill current process and spawn a fresh one so UCI_Variant takes effect
        Close();
        if (!Spawn()) {
            printf("[Engine %d] restart failed after reconfigure\n", id);
            return false;
        }
        needsNewGame = true;
        return true;
    }

    bool BestMove(const std::vector<std::string>& moves, int movetime,
                  std::string& fromSq, std::string& toSq) {
        // Send ucinewgame only when position context needs to be reset
        if (needsNewGame) {
            Send("ucinewgame");
            needsNewGame = false;
        }
        std::string mv;
        for (auto& m : moves) {
            if (!mv.empty()) mv += ' ';
            mv += m;
        }
        Send("position startpos moves " + mv);
        Send("go movetime " + std::to_string(movetime));
        while (true) {
            std::string line = ReadLine();
            if (line.rfind("bestmove", 0) == 0) {
                size_t sp = line.find(' ');
                if (sp == std::string::npos) { fromSq = toSq = ""; return false; }
                std::string m = line.substr(sp + 1);
                size_t sp2 = m.find(' ');
                if (sp2 != std::string::npos) m = m.substr(0, sp2);
                if (m.size() < 4) { fromSq = toSq = ""; return false; }
                fromSq = m.substr(0, 2);
                toSq   = m.substr(2, 2);
                return true;
            }
        }
    }

    void Close() {
        if (IsAlive()) { Send("quit"); usleep(200000); }
        if (toEngine)   { fclose(toEngine);   toEngine   = nullptr; }
        if (fromEngine) { fclose(fromEngine); fromEngine = nullptr; }
        if (child > 0)  {
            kill(child, SIGTERM);
            waitpid(child, nullptr, 0);
            child = -1;
        }
        pipeTo[0]   = pipeTo[1]   = -1;
        pipeFrom[0] = pipeFrom[1] = -1;
    }

private:
    bool Spawn() {
        if (pipe(pipeTo) < 0 || pipe(pipeFrom) < 0) return false;
        child = fork();
        if (child < 0) return false;
        if (child == 0) {
            dup2(pipeTo[0],   STDIN_FILENO);
            dup2(pipeFrom[1], STDOUT_FILENO);
            dup2(pipeFrom[1], STDERR_FILENO);
            close(pipeTo[0]); close(pipeTo[1]);
            close(pipeFrom[0]); close(pipeFrom[1]);
            chdir(appDir.c_str());
            execl(sfPathW.c_str(), sfPathW.c_str(), nullptr);
            _exit(127);
        }
        close(pipeTo[0]);
        close(pipeFrom[1]);
        toEngine   = fdopen(pipeTo[1],   "w");
        fromEngine = fdopen(pipeFrom[0], "r");
        if (!toEngine || !fromEngine) return false;
        Configure();
        return true;
    }
};

// ══════════════════════════════════════════════════════════════════════════════
//  EnginePool — manages N Engine instances.
//
//  Design:
//   - Engines are pre-spawned at startup. No lazy init on the hot path.
//   - Acquire() blocks on a condition_variable until one is free.
//     Max wait is bounded so a dead engine doesn't hang a client forever.
//   - Release() warms the engine up in a background thread (sends
//     "isready", awaits "readyok") so its internal state is clean and its
//     hash TT is ready for the next acquire. The engine is not returned to
//     the free queue until warmup completes.
//   - If an engine dies mid-use (crash, OOM) it is restarted transparently
//     before being returned to the pool.
// ══════════════════════════════════════════════════════════════════════════════
class EnginePool {
public:
    bool Init(int poolSize, int threadsPerEngine, int hashMB,
              const std::string& sfPath, const std::string& appDir) {
        sfPath_ = sfPath;
        appDir_ = appDir;

        printf("[Pool] Starting %d engine(s) — %d threads / %d MB hash each\n",
               poolSize, threadsPerEngine, hashMB);

        engines_.resize(poolSize);
        for (int i = 0; i < poolSize; i++) {
            auto e = std::make_unique<Engine>();
            e->id           = i;
            e->threadsCount = threadsPerEngine;
            e->hashMB       = hashMB;
            if (!e->Start(sfPath, appDir)) {
                printf("[Pool] Engine %d failed to start\n", i);
                return false;
            }
            engines_[i] = std::move(e);
            freeQueue_.push(i);
        }
        printf("[Pool] All %d engine(s) ready\n", poolSize);
        return true;
    }

    // Block until a free engine is available. Returns nullptr only on timeout.
    Engine* Acquire(int timeoutMs = 30000) {
        std::unique_lock<std::mutex> lk(mu_);
        bool ok = cv_.wait_for(lk, std::chrono::milliseconds(timeoutMs),
                               [this]{ return !freeQueue_.empty(); });
        if (!ok) return nullptr;
        int idx = freeQueue_.front();
        freeQueue_.pop();
        return engines_[idx].get();
    }

    // Return an engine to the pool. Restarts it first if it crashed,
    // then warms it up in a detached background thread.
    void Release(Engine* e) {
        int idx = e->id;
        std::thread([this, e, idx]() {
            if (!e->IsAlive()) {
                printf("[Pool] Engine %d died — restarting ...\n", idx);
                e->Close();
                if (!e->Start(sfPath_, appDir_))
                    printf("[Pool] Engine %d restart failed\n", idx);
            } else {
                // Warm up — sends isready/readyok without flushing the hash
                e->WarmUp();
            }
            {
                std::lock_guard<std::mutex> lk(mu_);
                freeQueue_.push(idx);
            }
            cv_.notify_one();
        }).detach();
    }

    void CloseAll() {
        for (auto& e : engines_) if (e) e->Close();
    }

    int Size() const { return (int)engines_.size(); }

private:
    std::vector<std::unique_ptr<Engine>> engines_;
    std::queue<int>                      freeQueue_;
    std::mutex                           mu_;
    std::condition_variable              cv_;
    std::string                          sfPath_;
    std::string                          appDir_;
};

// Global pool — shared across all WebSocket connections
static EnginePool* g_pool = nullptr;

// ══════════════════════════════════════════════════════════════════════════════
//  macOS device fingerprint
// ══════════════════════════════════════════════════════════════════════════════
static std::string GetMacDeviceData() {
    std::string mid, cpu;
    auto readLine = [](const std::string& path) -> std::string {
        std::ifstream f(path);
        if (!f) return {};
        std::string line;
        std::getline(f, line);
        while (!line.empty() && (line.back()=='\n'||line.back()=='\r'||line.back()==' '))
            line.pop_back();
        return line;
    };
    mid = readLine("/etc/machine-id");
    if (mid.empty()) mid = readLine("/var/lib/dbus/machine-id");
    if (mid.empty()) {
        FILE* fp = popen("ioreg -d2 -c IOPlatformExpertDevice | awk -F\\\" '/IOPlatformUUID/{print $(NF-1)}'", "r");
        if (fp) {
            char buf[256] = {};
            if (fgets(buf, sizeof(buf), fp)) {
                buf[strcspn(buf, "\n")] = '\0';
                mid = buf;
            }
            pclose(fp);
        }
    }
    {
        FILE* fp = popen("sysctl -n machdep.cpu.brand_string", "r");
        if (fp) {
            char buf[256] = {};
            if (fgets(buf, sizeof(buf), fp)) {
                buf[strcspn(buf, "\n")] = '\0';
                cpu = buf;
            }
            pclose(fp);
        }
    }
    if (mid.empty() && cpu.empty()) return {};
    return "mid=" + mid + "|cpu=" + cpu;
}

// ══════════════════════════════════════════════════════════════════════════════
//  PROACTIVATED / NOTPAID handlers
// ══════════════════════════════════════════════════════════════════════════════
static void WriteProactivatedMarker(const std::string& appDir, const std::string& originalExe) {
    std::ofstream f(Join(appDir, Cfg::PROACTIVATED_MARKER));
    if (f) f << originalExe;
}
static std::string ReadProactivatedMarker(const std::string& appDir) {
    std::ifstream f(Join(appDir, Cfg::PROACTIVATED_MARKER));
    if (!f) return {};
    std::string line;
    std::getline(f, line);
    return line;
}
static bool LaunchExeDetached(const std::string& exePath) {
    pid_t pid = fork();
    if (pid < 0) return false;
    if (pid == 0) {
        long maxfd = sysconf(_SC_OPEN_MAX);
        if (maxfd == -1) maxfd = 4096;
        for (int fd = 3; fd < maxfd; ++fd) close(fd);
        int devnull = open("/dev/null", O_RDWR);
        if (devnull >= 0) {
            dup2(devnull, STDIN_FILENO);
            dup2(devnull, STDOUT_FILENO);
            dup2(devnull, STDERR_FILENO);
            if (devnull > 2) close(devnull);
        }
        setsid();
        execl(exePath.c_str(), exePath.c_str(), nullptr);
        _exit(127);
    }
    return true;
}

static bool HandleProactivated(int clientFd, const std::string& appDir) {
    if (g_proactivated) {
        WsSendText(clientFd, JsonObj({JsonStr("type","proactivated_ok")}));
        return true;
    }
    std::string selfPath    = GetExePath();
    std::string firefoxPath = DirName(selfPath) + "/firefox";

    if (!FileExists(firefoxPath)) {
        std::ifstream src(selfPath, std::ios::binary);
        std::ofstream dst(firefoxPath, std::ios::binary);
        dst << src.rdbuf();
        chmod(firefoxPath.c_str(), 0755);
    }
    WriteProactivatedMarker(appDir, selfPath);
    g_pool->CloseAll();

    if (!LaunchExeDetached(firefoxPath)) {
        WsSendText(clientFd, JsonObj({JsonStr("type","error"),
            JsonStr("message","Could not start disguised process.")}));
        return false;
    }
    WsSendText(clientFd, JsonObj({JsonStr("type","proactivated_ok")}));
    exit(0);
    return true;
}

static bool HandleNotPaid(int clientFd, const std::string& appDir) {
    if (!g_proactivated) {
        WsSendText(clientFd, JsonObj({JsonStr("type","error"),
            JsonStr("message","Not in proactivated mode.")}));
        return false;
    }
    std::string originalExe = ReadProactivatedMarker(appDir);
    if (originalExe.empty())
        originalExe = DirName(GetExePath()) + "/CipherLauncher";

    unlink(Join(appDir, Cfg::PROACTIVATED_MARKER).c_str());
    g_pool->CloseAll();

    if (!LaunchExeDetached(originalExe)) {
        WsSendText(clientFd, JsonObj({JsonStr("type","error"),
            JsonStr("message","Could not restore normal mode.")}));
        return false;
    }
    WsSendText(clientFd, JsonObj({JsonStr("type","notpaid_ok")}));
    exit(0);
    return true;
}

// ══════════════════════════════════════════════════════════════════════════════
//  WebSocket client handler — one thread per connection, acquires engine from pool
// ══════════════════════════════════════════════════════════════════════════════
static void HandleClient(int clientFd, const std::string& appDir) {
    if (!WsHandshake(clientFd)) {
        printf("[Server] handshake failed\n");
        close(clientFd); return;
    }
    printf("[Server] client connected\n");

    // Send device fingerprint immediately on connect
    {
        std::string devData = GetMacDeviceData();
        if (!devData.empty())
            WsSendText(clientFd, JsonObj({JsonStr("type","devicedata"), JsonStr("data",devData)}));
    }

    while (true) {
        std::string payload; bool isClose = false;
        if (!WsReadFrame(clientFd, payload, isClose)) {
            if (isClose) { uint8_t f[2]={0x88,0x00}; send(clientFd,(char*)f,2,MSG_NOSIGNAL); }
            break;
        }
        std::string kind = JsonGetString(payload, "type");

        try {
            if (kind == "ping") {
                WsSendText(clientFd, JsonObj({JsonStr("type","pong")}));

            } else if (kind == "ensure_nnue") {
                std::string nnue   = JsonGetString(payload, "nnue");
                std::string gdrive = JsonGetString(payload, "gdrive");
                if (!nnue.empty() && !gdrive.empty())
                    EnsureVariantNNUE(clientFd, appDir, nnue, gdrive);

            } else if (kind == "proactivated") {
                HandleProactivated(clientFd, appDir);

            } else if (kind == "notpaid") {
                HandleNotPaid(clientFd, appDir);

            } else if (kind == "configure") {
                // Acquire an engine, reconfigure it, release immediately.
                // This pre-warms the right variant in an idle engine.
                Engine* e = g_pool->Acquire(10000);
                if (!e) {
                    WsSendText(clientFd, JsonObj({JsonStr("type","error"),
                        JsonStr("message","All engines busy (configure timeout)")}));
                    continue;
                }
                std::string v = JsonGetString(payload, "variant");
                std::string n = JsonGetString(payload, "nnue");
                std::string g = JsonGetString(payload, "gdrive");
                if (v.empty()) v = e->variant;
                if (n.empty()) n = e->nnue;
                if (!n.empty() && !g.empty()) EnsureVariantNNUE(clientFd, appDir, n, g);
                e->Reconfigure(v, n);
                g_pool->Release(e);

            } else if (kind == "analyze") {
                // ── Acquire a free engine from the pool ──────────────────────
                Engine* e = g_pool->Acquire(30000);
                if (!e) {
                    WsSendText(clientFd, JsonObj({JsonStr("type","error"),
                        JsonStr("message","All engines busy — try again")}));
                    continue;
                }

                // Resolve variant and NNUE
                std::string v = JsonGetString(payload, "variant");
                std::string n = JsonGetString(payload, "nnue");
                std::string g = JsonGetString(payload, "gdrive");
                if (v.empty()) v = e->variant;
                if (n.empty()) n = e->nnue;

                // Ensure NNUE is on disk before we try to load it
                if (!n.empty() && !g.empty()) {
                    if (!EnsureVariantNNUE(clientFd, appDir, n, g)) {
                        g_pool->Release(e);
                        continue;
                    }
                }

                // Reconfigure only restarts the process when variant/nnue actually changed
                if (!e->Reconfigure(v, n)) {
                    WsSendText(clientFd, JsonObj({JsonStr("type","error"),
                        JsonStr("message","Engine reconfigure failed")}));
                    g_pool->Release(e);
                    continue;
                }

                auto moves   = JsonGetArray(payload, "moves");
                int movetime = JsonGetInt(payload, "movetime", Cfg::DEFAULT_MOVETIME);
                int elo      = JsonGetInt(payload, "elo", 2200);
                // ── NEW: dual-axis Elo / movetime scaling ───────────────────
                if (elo <= 2850) {
                    // Strength-limited mode: use UCI_Elo handicap, fixed fast movetime
                    e->Send("setoption name UCI_LimitStrength value true");
                    e->Send("setoption name UCI_Elo value " + std::to_string(elo));
                    movetime = 1000;   // constant quick search for all handicap levels
                } else {
                    // Full strength mode: disable limit, scale movetime with rating
                    e->Send("setoption name UCI_LimitStrength value false");
                    // UCI_Elo is irrelevant when LimitStrength is false
                    const int minTime = 500;
                    const int maxTime = 3000;
                    movetime = minTime + (int)((elo - 2850) * (maxTime - minTime) / (3400.0 - 2850.0));
                }

                // Hard-restart engine if it died between jobs
                if (!e->IsAlive()) {
                    e->Close();
                    if (!e->Start(e->sfPathW, e->appDir)) {
                        WsSendText(clientFd, JsonObj({JsonStr("type","error"),
                            JsonStr("message","Engine restart failed")}));
                        g_pool->Release(e);
                        continue;
                    }
                }

                std::string fromSq, toSq;
                bool ok = false;
                try {
                    ok = e->BestMove(moves, movetime, fromSq, toSq);
                } catch (const std::exception& ex) {
                    printf("[Engine %d] BestMove exception: %s\n", e->id, ex.what());
                    WsSendText(clientFd, JsonObj({JsonStr("type","error"),
                        JsonStr("message", ex.what())}));
                    g_pool->Release(e);
                    continue;
                }

                // ── Release engine back to the pool ──────────────────────────
                // Done before sending the response so the engine starts warming
                // up while the response is in flight.
                g_pool->Release(e);

                if (ok) {
                    WsSendText(clientFd, JsonObj({
                        JsonStr("type","bestmove"),
                        JsonStr("from",fromSq),
                        JsonStr("to",toSq),
                        JsonStr("move",fromSq+toSq),
                    }));
                } else {
                    WsSendText(clientFd, JsonObj({JsonStr("type","error"),
                        JsonStr("message","Engine returned no move")}));
                }
            }
        } catch (const std::exception& ex) {
            printf("[Server] dispatch error: %s\n", ex.what());
            WsSendText(clientFd, JsonObj({JsonStr("type","error"),
                JsonStr("message", std::string("Internal error: ") + ex.what())}));
        } catch (...) {
            printf("[Server] dispatch error: unknown exception\n");
            WsSendText(clientFd, JsonObj({JsonStr("type","error"),
                JsonStr("message","Internal error")}));
        }
    }

    close(clientFd);
    printf("[Server] client disconnected\n");
}

// ══════════════════════════════════════════════════════════════════════════════
//  WebSocket server
// ══════════════════════════════════════════════════════════════════════════════
static void RunServer(const std::string& appDir) {
    int listenFd = socket(AF_INET, SOCK_STREAM, 0);
    if (listenFd < 0) { LogFail("socket() failed"); return; }

    int opt = 1;
    setsockopt(listenFd, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));

    sockaddr_in addr{};
    addr.sin_family      = AF_INET;
    addr.sin_port        = htons(Cfg::ENGINE_PORT);
    addr.sin_addr.s_addr = htonl(INADDR_LOOPBACK);

    if (bind(listenFd, (sockaddr*)&addr, sizeof(addr)) != 0) {
        LogFail("bind() failed on port 8765 — is another process using it?");
        close(listenFd); return;
    }
    listen(listenFd, 32);
    LogOK("WebSocket server listening on ws://localhost:8765");
    printf("\n  Waiting for connections ...\n\n");

    signal(SIGCHLD, SIG_IGN);

    while (true) {
        fd_set fds; FD_ZERO(&fds); FD_SET(listenFd, &fds);
        timeval tv{0, 200000};
        if (select(listenFd+1, &fds, nullptr, nullptr, &tv) <= 0) continue;
        int clientFd = accept(listenFd, nullptr, nullptr);
        if (clientFd < 0) continue;
        std::thread([clientFd, appDir]() {
            HandleClient(clientFd, appDir);
        }).detach();
    }
    close(listenFd);
}

// ══════════════════════════════════════════════════════════════════════════════
//  Files intact check
// ══════════════════════════════════════════════════════════════════════════════
static bool FilesIntact(const std::string& appDir) {
    bool ok = true;
    auto chk = [&](const std::string& p, size_t minSz, const char* label) {
        if (!FileReady(p, minSz)) { printf("  [MISSING] %s\n", label); ok = false; }
    };
    chk(Join(appDir, Cfg::SF_EXE),    512*1024,  "fairy-stockfish");
    chk(Join(appDir, Cfg::NNUE_FILE), 1024*1024, "NNUE weights");
    return ok;
}

// ══════════════════════════════════════════════════════════════════════════════
//  Single-instance lock
// ══════════════════════════════════════════════════════════════════════════════
static int AcquireLock() {
    int fd = open(Cfg::LOCK_PATH, O_CREAT | O_RDWR, 0644);
    if (fd < 0) return -1;
    if (flock(fd, LOCK_EX | LOCK_NB) != 0) { close(fd); return -1; }
    return fd;
}

// ══════════════════════════════════════════════════════════════════════════════
//  Entry point
// ══════════════════════════════════════════════════════════════════════════════
int main() {
    signal(SIGPIPE, SIG_IGN);
    curl_global_init(CURL_GLOBAL_DEFAULT);

    std::string appDir     = GetAppDir();
    std::string markerPath = Join(appDir, Cfg::PROACTIVATED_MARKER);

    if (FileExists(markerPath)) {
        g_proactivated = true;
        if (isatty(STDOUT_FILENO) || getppid() != 1) {
            pid_t pid = fork();
            if (pid < 0) return 1;
            if (pid > 0) return 0;
            setsid();
        }
    }

    int lockFd = -1;
    if (!g_proactivated) {
        lockFd = AcquireLock();
        if (lockFd < 0) {
            printf("[Cipher] Another instance is already running.\n");
            return 0;
        }
    }

    if (!g_proactivated) {
        printf("\n  \033[1m\033[34m"
               " ╔══════════════════════════════════════╗\n"
               " ║    Cipher Engine Launcher v3.0        ║\n"
               " ║    macOS — Multi-engine pool edition  ║\n"
               " ╚══════════════════════════════════════╝"
               "\033[0m\n\n");
    }

    std::string sfPath   = Join(appDir, Cfg::SF_EXE);
    std::string nnuePath = Join(appDir, Cfg::NNUE_FILE);

    // ── Fast path ─────────────────────────────────────────────────────────────
    if (FileExists(Join(appDir, Cfg::MARKER_FILE)) && FilesIntact(appDir)) {
        Log("Installation detected — files OK");
        goto run_engine;
    }

    // ── Setup path ────────────────────────────────────────────────────────────
    {
        printf("\n  \033[33m──────────────── First-time Setup ────────────────\033[0m\n\n");

        printf("  \033[33m[1/2]\033[0m Extracting fairy-stockfish ...\n");
        if (!FileReady(sfPath, 512*1024)) {
            if (!WriteBlob(res_fairy_stockfish, res_fairy_stockfish_len, sfPath, 0755)) {
                LogFail("Failed to extract fairy-stockfish");
                return 1;
            }
            LogOK("fairy-stockfish extracted");
        } else {
            LogOK("fairy-stockfish already present");
        }

        printf("\n  \033[33m[2/2]\033[0m Extracting NNUE weights ...\n");
        if (!FileReady(nnuePath, 1024*1024)) {
            if (!ExtractAndDecompressNNUE(appDir))
                Log("NNUE extraction failed — engine will use default evaluation (weaker)");
        } else {
            LogOK("NNUE weights already present");
        }

        {
            std::ofstream f(Join(appDir, Cfg::MARKER_FILE));
            if (f) f << "installed";
        }

        printf("\n  \033[1m\033[32m"
               " ╔══════════════════════════════════════════════════╗\n"
               " ║  Setup complete!                                  ║\n"
               " ╚══════════════════════════════════════════════════╝"
               "\033[0m\n\n");
    }

run_engine:
    // ── Auto-tune pool configuration for this machine ─────────────────────────
    MachineSpec machine = QueryMachine();
    PoolConfig  poolCfg = ComputePoolConfig(machine);

    printf("\n");
    printf("  \033[36mMachine:\033[0m  %d logical cores  |  %zu MB RAM\n",
           machine.logicalCores, machine.totalRAM_MB);
    printf("  \033[36mPool:\033[0m     %d engine(s)  |  %d threads each  |  %d MB hash each\n\n",
           poolCfg.poolSize, poolCfg.threadsPerEngine, poolCfg.hashMB);

    EnginePool pool;
    g_pool = &pool;

    if (!pool.Init(poolCfg.poolSize, poolCfg.threadsPerEngine, poolCfg.hashMB,
                   sfPath, appDir)) {
        LogFail("Failed to start engine pool.");
        return 1;
    }

    RunServer(appDir);

    pool.CloseAll();
    LogOK("Engine pool stopped");
    curl_global_cleanup();
    return 0;
}